[project]
name = "agno-agent-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agno>=2.0.5",
    "fastapi[standard]>=0.116.2",
    "ollama>=0.5.4",
    "sqlalchemy>=2.0.43",
]
